name: Update dev.json

on:
  push:
    branches:
      - main 

jobs:
  update_manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout releases repo
        uses: actions/checkout@v4
        with:
          repository: dangi13/releases 
          ref: main
          persist-credentials: true 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update dev.json
        run: |
          jq '.["repo_A"] = {"hellos": "bye"}' manifests/dev.json > manifests/dev.json.tmp
          mv manifests/dev.json.tmp manifests/dev.json

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "dangi13+github-actions@@users.noreply.github.com"
          git add manifests/dev.json
          git commit -m "Update repo_A data in dev.json"
          git push origin main