name: Update dev.json

on:
  workflow_dispatch:

jobs:
  update_manifest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      deployments: write
    steps:
      - name: Checkout releases repo
        uses: actions/checkout@v3
        with:
          repository: dangi13/releases 
          ref: main
          persist-credentials: true 
          keyfile: ${{ secrets.GITHUB_TOKEN }}

      - name: Update dev.json
        run: |
          jq '.["repo_A"] = {"hello": "bye"}' manifests/dev.json > manifests/dev.json.tmp
          mv manifests/dev.json.tmp manifests/dev.json

      -name: Clear Git credentials cache
       run: |
         git config --unset credential.helper
        
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add manifests/dev.json
          git commit -m "Update repo_A data in dev.json"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}